### ISSUE TITLE
virsorter2 container fails with "Permission denied: '/db/group' "

### ISSUE THREAD

**Issue by papanikos** [replikation/What_the_Phage#121]
Hi,
I am running:
```
nextflow run ./What_the_Phage-1.0.0/phage.nf -profile slurm,singularity \
--databases --workdir --cachedir ..
```
Versions:
nextflow: 20.07.1
singularity: 3.6

and getting all tasks for virsorter2 failing with: 
```
$ cat .command.err
Traceback (most recent call last):
  File "/opt/conda/bin/virsorter", line 10, in <module>
    sys.exit(cli())
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/virsorter/virsorter.py", line 207, in run_workflow
    tmpdir=tmpdir, min_length=min_length, min_score=min_score,
  File "/opt/conda/lib/python3.7/site-packages/virsorter/config.py", line 70, in make_config
    groups_avail = os.listdir(f'{db_dir}/group')
PermissionError: [Errno 13] Permission denied: '/db/group'
```

Permissions inside the container
```
$ singularity shell multifractal-virsorter2-0-1.img
Singularity> ls -alh /db
Singularity> ls -alh /db
total 28K
drwxr-xr-x  8 nikos users 4.0K Oct  7 15:48 .
drwxr-xr-x 24 nikos users  600 Nov 26 14:33 ..
drwxr-xr-x  2 nikos users 4.0K Oct  7 15:44 .empty
drwxr-xr-x  8 nikos users 4.0K Oct  7 15:42 .snakemake
-rw-r--r--  1 nikos users    0 Oct  7 15:48 Done_all_setup
drwxr-xr-x  3 nikos users 4.0K Oct  7 15:42 conda_envs
drwxr-x---  7 nikos users 4.0K May 11  2020 group
drwxr-x---  4 nikos users 4.0K May 11  2020 hmm
drwxr-x---  2 nikos users 4.0K May 11  2020 rbs
```

Am I the only one that runs into this?

Would a 
```
chmod -R o+rX /db
```
solve it when building the container?

Would you happen to know if I can I set permissions for dirs in a pre-built image?

**Comment by replikation** [comment]
* hi where is `/db/group`  located? What's the permission on `/db/group` ?
* also your command looks strange, "paths infos" are missing

````bash
nextflow run ./What_the_Phage-1.0.0/phage.nf -profile slurm,singularity \
--databases $missingPath --workdir $missingPath --cachedir ..
````
usually its something like this, e.g.:

````bash
nextflow run ./What_the_Phage-1.0.0/phage.nf -profile slurm,singularity \
--databases /home/$USER/databases --workdir /tmp/workdir --cachedir ../singularity_images
````

**Comment by papanikos** [comment]
My paths are there I just excluded them for brevity, sorry for the confusion.

The `singularity shell <path_to_img>` allows me to run an interactive shell within the container.
The `/db/groups` is a path inside the container created according to the dockerfile on https://hub.docker.com/r/multifractal/virsorter-2/dockerfile with
```
Run virsorter setup -d db -j 4
```

**Comment by replikation** [comment]
* okay thanks for the clarifications, we work on a fix
