### ISSUE TITLE
Add Phigaro?

### ISSUE THREAD

**Issue by chris-rands** [replikation/What_the_Phage#88]
Nice tool and idea. Perhaps our phigaro tool could also be included (although I appreciate that adding new tools is probably not trivial):
https://academic.oup.com/bioinformatics/article/36/12/3882/5822875

https://github.com/bobeobibo/phigaro

**Comment by chris-rands** [comment]
Ah closing as a duplicate of #1 and #75

**Comment by replikation** [comment]
ah yep, you were faster, thanks for the interest and suggestion :)

**Comment by replikation** [comment]
@chris-rands the most time-consuming part is writing a parser for the tools and check/validate the tool output
so we would need: 
1) a working dockerfile / container (for both docker and singularity)
2) a parser which gets us a simple list of contigs(one contig per line) that are considered "phage positive"
   * and can be used to extract the contigs via samtools
   * some tools rename contigs which make things complicated ;)
3) (if applicable) database download location for the tool 

* if we have these code snippets and information an inclusion is quite trivial on our side

**Comment by PollyTikhonova** [comment]
Hello, I am the Phigaro dev.  I wanted to ask, what do you mean when you say contigs? Is it something that you transform initial data in? or is it a prophage region which phigaro detects?
I was trying to understand it on my own, but I can't launch your program ( I meet with the error:

```nextflow run replikation/What_the_Phage -r v0.8.0 --cores 40 -profile local,singularity --dv --ma --vn --vb --pp --sm --output /home/tikhonova/test_wtp --fastq /home/tikhonova/test_wtp/ERR575691_raw_assembly.fasta.gz```

``N` E X T F L O W  ~  version 20.07.1 
Launching `replikation/What_the_Phage` [high_panini] - revision: 84e10a25c6 [v0.8.0]
Unknown method invocation `div` on ConfigObject type``

Jul-30 15:48:41.992 [main] DEBUG nextflow.cli.Launcher - $> nextflow run replikation/What_the_Phage -r v0.8.0 --cores 40 -profile local,singularity --dv --ma --vn --vb --pp --sm --output /home/tikhonova/test_wtp --fastq /home/tikhonova/test_wtp/ERR575691_raw_assembly.fasta.gz
Jul-30 15:48:42.054 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 20.07.1
Jul-30 15:48:42.475 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/tikhonova/.nextflow/assets/replikation/What_the_Phage/.git/config; branch: master; remote: origin; url: https://github.com/replikation/What_the_Phage.git
Jul-30 15:48:42.485 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/tikhonova/.nextflow/assets/replikation/What_the_Phage/.git/config; branch: master; remote: origin; url: https://github.com/replikation/What_the_Phage.git
Jul-30 15:48:42.763 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/tikhonova/.nextflow/assets/replikation/What_the_Phage/.git/config; branch: master; remote: origin; url: https://github.com/replikation/What_the_Phage.git
Jul-30 15:48:42.764 [main] INFO  nextflow.cli.CmdRun - Launching `replikation/What_the_Phage` [high_panini] - revision: 84e10a25c6 [v0.8.0]
Jul-30 15:48:43.456 [main] DEBUG nextflow.config.ConfigBuilder - Found config base: /home/tikhonova/.nextflow/assets/replikation/What_the_Phage/nextflow.config
Jul-30 15:48:43.457 [main] DEBUG nextflow.config.ConfigBuilder - Found config local: /home/tikhonova/test_wtp/nextflow.config
Jul-30 15:48:43.457 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/tikhonova/.nextflow/assets/replikation/What_the_Phage/nextflow.config
Jul-30 15:48:43.457 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/tikhonova/test_wtp/nextflow.config
Jul-30 15:48:43.463 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `local,singularity`
Jul-30 15:48:43.656 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `local,singularity`
Jul-30 15:48:43.686 [main] ERROR nextflow.cli.Launcher - Unable to parse config file: '/home/tikhonova/test_wtp/nextflow.config'

  No signature of method: groovy.util.ConfigObject.div() is applicable for argument types: (ConfigObject) values: [[:]]
  Possible solutions: min(groovy.lang.Closure), is(java.lang.Object), wait(), size(), find(), dump()

groovy.lang.MissingMethodException: No signature of method: groovy.util.ConfigObject.div() is applicable for argument types: (ConfigObject) values: [[:]]
Possible solutions: min(groovy.lang.Closure), is(java.lang.Object), wait(), size(), find(), dump()
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:70)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:49)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at _nf_config_fba93312.run(_nf_config_fba93312:1)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
	at org.codehaus.groovy.reflection.CachedMethod$invoke.call(Unknown Source)
	at nextflow.config.ConfigParser$_parse_closure5.doCall(ConfigParser.groovy:417)
	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaMethod.invoke(ClosureMetaMethod.java:83)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1126)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.DelegatingMetaClass.invokeMethod(DelegatingMetaClass.java:147)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:37)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119)
	at nextflow.config.ConfigParser.parse(ConfigParser.groovy:445)
	at nextflow.config.ConfigParser$parse$0.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at nextflow.config.ConfigParser$parse$0.callCurrent(Unknown Source)
	at nextflow.config.ConfigParser.parse(ConfigParser.groovy:300)
	at nextflow.config.ConfigParser$parse$5.call(Unknown Source)
	at nextflow.config.ConfigBuilder.parse0(ConfigBuilder.groovy:406)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:176)
	at nextflow.config.ConfigBuilder.merge0(ConfigBuilder.groovy:392)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:184)
	at nextflow.config.ConfigBuilder.buildConfig0(ConfigBuilder.groovy:342)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:176)
	at nextflow.config.ConfigBuilder.buildGivenFiles(ConfigBuilder.groovy:306)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:168)
	at nextflow.config.ConfigBuilder.buildConfigObject(ConfigBuilder.groovy:710)
	at nextflow.config.ConfigBuilder.build(ConfigBuilder.groovy:723)
	at nextflow.script.ScriptRunner.<init>(ScriptRunner.groovy:85)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:255)
	at nextflow.cli.Launcher.run(Launcher.groovy:466)
	at nextflow.cli.Launcher.main(Launcher.groovy:648)

**Comment by replikation** [comment]
hi, thank you for the interest.
the error you reported (before editing) was probably from the newest nextflow release, please use for Release v0.8.1 [NEXTFLOW version 20.01.0 or 20.04.1]. nextflow 20.07.x will be supported in our next release (currently testing that).

I mean fasta entries/names in a multifasta file. WtP reports which of these fasta entries are phages.

It would help if you could give us a good "best practice" command to identify which fasta contains phages/prophages.
And of which result file we could extract easily the names of these positive phages (the fasta header, e.g. `>fasta_1`).

**Comment by PollyTikhonova** [comment]
Oh! WTP finished the work  (with a ruin((( ) but still, it managed to produce some data, so do I understand correctly that you need a file like those in a folder ``identified_contigs_by_tools`` ?

**Comment by replikation** [comment]
ad.1 glad to hear its working
ad.2 this information is currently not needed but as it seems useful, I think we will add that too at some point (i keep that in mind for now). the complete "raw tool output" is either way completely stored too so the User can check specifically the output from your tool if they want to
* also we are currently discussing how to best implement prophage detection for the user to be as convenient as possible, so the coordinates of prophages in a fasta sequence would be useful for that.
ad.3. no, we don't need a specific output files, can be any file e.g. output.txt ( we need to rename it either way). This needs to contain a list of header names, without ">", one fasta header name per line (unmodified from the original input)

e.g.:

```bash
fasta_1
fasta_2
fasta_5
```

yep you can use https://github.com/mult1fractal/WtP_test-data 
 

Thank you very much

**Comment by PollyTikhonova** [comment]
Ok, I understand! Thank you very much for your responses)))

**Comment by PollyTikhonova** [comment]
Hello, 
I did everything you asked:
1. Dockerfile and Singularity file.
1.1 About Singularity:
      For Singularity a couple of paths (PATH and HOME) should be exported, you can find them in the Singularity file. So, you can built a Singularity image from the file or from docker repository and export the paths after. Or you can omit the exporting path step and use the full path Phigaro calling (with specifying a full path to a config file) - I represent the codes below.
2. Parser
- You can call Phigaro in a short way (if all paths (PATH and HOME) are installed correctly) \
 ```phigaro -f [PATH_TO_INPUT_MULTIFASTA] -o [PATH_TO_OUTPUT_FOLDER] -t [THREADS (OPTIONAL)] --wtp```
- Or you can call Phigaro in a full path way \
 `/root/miniconda3/bin/phigaro -f [PATH_TO_INPUT_MULTIFASTA] -o [PATH_TO_OUTPUT_FOLDER] -t [THREADS (OPTIONAL)] --wtp --config /root/.phigaro/config.yml` \
It will create the folder that you specify with `-o` (if it doesn't exist), and there you will find the `phigaro.txt` file with the names of the phage containing fasta sequences and the folder with standart phigaro outputs.

_By the way, I noticed that What_The_Phage changes the names of the phage positive sequences - at least it replaces the last dot with a dash. But Phigaro does not change anything, as you asked._

3. Database download location
All external files, Phigaro downloads during the setup process and stores in `~/.phigaro/pvog`, are available by [the link](http://download.ripcm.com/phigaro/).\
But I am not sure if you really need this because Phigaro is fully setuped in a Docker container with all external files.


Please, let me know if you have any problems or you need anything)

**Comment by mult1fractal** [comment]
Hej,
many thanks for your great effort!
We will take care of the rest 👍 
I will start integrating Phigaro on Monday

**Comment by mult1fractal** [comment]
@PollyTikhonova : Phigaro is basically fully integrated into WtP
I just have to update some minor issues in my pull request #98   and we will release a new version of WtP with your tool 👍 
Thanks to your effort it was really easy!

considerations:
* We are currently using your Dockerfile tikhonovapolly/phigaro:v2.2.6
* Is it possible to send us the "Raw Dockerfile"[with all the installation commands] so we can build and maintain it? 
  * why? because Docker Hub will soon have a [Container Image Retention Policy](https://www.docker.com/pricing/retentionfaq) (1 November 2020 ) and we have a pro account for Dockerhub

**Comment by PollyTikhonova** [comment]
Very happy to hear that! We'll wait for your release)))
Sorry, I am not a very experienced Docker user, so I need to ask what do you mean "raw docker" ? How raw should it be? 
As far as I remember, the initial phigaro image was built based on somebody's hmmer docker container and I think that's not you are asking for, am I right?  
 - So, should I generate a raw docker from Ubuntu image? 
 - And one more question: is it urgent? or you'll release now as is and do all this Docker staff a bit later? (I just need to plan my work processes)
 - Good point about databases! But wouldn't it be really time consuming to download them every time the user runs WtP? or you will download them once with the WtP installation process and then volume them to the docker container?

**Comment by mult1fractal** [comment]
No Problem  I can take care of it 👍 
For the moment, it's fine with your Dockerfile.
When I updated my PR I think we will release the new Version
The Dockerfile we will maintain is a long term goal when Dockerhub will update its policy

* I  basically just need the commands to build the working Dockerfile eg.:
```Docker
From xyz
RUN apt-get install -y wget procps python

RUN pip install phigaro
```

Database:
* We download the database once. 
  * First execution of WtP - download all databases 
  * every other execution databases are available and you can tell WtP where the databases are located on your system

* eg. : the database for Phigaro will be downloaded once
  *  in nextflow we can basically "mount" the database into the Phigaro module which is the Dockerfile in general

* But this is something I have to test (Dockerfile with database or Dockerfile without database  and "mounting the database" )
* A  ```--wtp /path/to/database``` would be ideal for the Dockerfile without database in terms of speed (but this is sth. I have to discuss with @replikation )

**Comment by PollyTikhonova** [comment]
@mult1fractal 
 - I have a thought about reducing the size of docker: the thing is that for the work with raw data Phigaro demands hmmer and Prodigal preinstallled, but there's an option to provide already computed data by hmmer and prodigal  as an input for Phigaro. As I remember, WtP uses this tools too, so, theoretically, we can exclude this tools from docker and left just Phigaro. But, of course, this could affect the scalability and uniformity of your tool, that is maybe not good. But you can just take into account this option.
- about --wtp /path/to/database: Phigaro has an option to provide a text configuration file with any custom paths. I think, this could work. But if it is not I'll add your UX scenario if you ask)

**Comment by mult1fractal** [comment]
@PollyTikhonova 
Hey I'm currently preparing our WtP preprint for submission.
I was wondering how you filter the phage positive sequences for the --wtp output
(above which (and what) cut-off it is a phage-sequence)
  
e.g. 
Tool | Criteria | Filter|
|-|-|-|
Virsorter | Category of detection (1, 2 or 3: intact, incomplete or questionable) |Category 1 & 2|
Phigaro|?|?|

**Comment by PollyTikhonova** [comment]
While the wtp option Phigaro is working in its basic mode, so the thresolds for the final score are
• Minimum score threshold: 45.39
• Maximum score threshold: 46.0

Briefly, the final score is computed as a product of phage concentration score and triangled GC content score [each of the scores were filtered by indicator function].

**Comment by mult1fractal** [comment]
Thank you very much:)
